# Generated by Django 3.0.9 on 2021-05-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpage',
            name='content_selector',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
